
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DPUNT = 32;
  public static final int OVER = 5;
  public static final int GE = 10;
  public static final int INTEGER = 30;
  public static final int LPAREN = 19;
  public static final int SEMI = 17;
  public static final int REPEAT = 25;
  public static final int FOR = 24;
  public static final int MINUS = 3;
  public static final int WRITE = 36;
  public static final int RPAREN = 20;
  public static final int NOT = 15;
  public static final int AND = 13;
  public static final int LT = 7;
  public static final int OR = 14;
  public static final int COMMA = 18;
  public static final int BEGIN = 27;
  public static final int UNTIL = 26;
  public static final int NUM = 39;
  public static final int PLUS = 2;
  public static final int ASSIGN = 16;
  public static final int IF = 21;
  public static final int ID = 40;
  public static final int LE = 8;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int MOD = 6;
  public static final int EQ = 11;
  public static final int TIMES = 4;
  public static final int ELSE = 23;
  public static final int READ = 35;
  public static final int TO = 33;
  public static final int THEN = 22;
  public static final int NE = 12;
  public static final int END = 28;
  public static final int FALSE = 38;
  public static final int GT = 9;
  public static final int VAR = 29;
  public static final int DO = 34;
  public static final String[] terminalNames = new String[] {
          "EOF",
          "error",
          "PLUS",
          "MINUS",
          "TIMES",
          "OVER",
          "MOD",
          "LT",
          "LE",
          "GT",
          "GE",
          "EQ",
          "NE",
          "AND",
          "OR",
          "NOT",
          "ASSIGN",
          "SEMI",
          "COMMA",
          "LPAREN",
          "RPAREN",
          "IF",
          "THEN",
          "ELSE",
          "FOR",
          "REPEAT",
          "UNTIL",
          "BEGIN",
          "END",
          "VAR",
          "INTEGER",
          "BOOLEAN",
          "DPUNT",
          "TO",
          "DO",
          "READ",
          "WRITE",
          "TRUE",
          "FALSE",
          "NUM",
          "ID"
  };
}

